application: chachara
version: 1
runtime: python27
api_version: 1

threadsafe: no

handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static
  static_dir: static

- url: /.*
  script: boot.py
